set_property IOSTANDARD LVCMOS33 [get_ports Q]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports Qn]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports T]
set_property PACKAGE_PIN V8 [get_ports rst_n]
set_property PACKAGE_PIN K14 [get_ports Q]
set_property PACKAGE_PIN K13 [get_ports Qn]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property PACKAGE_PIN Y7 [get_ports T]

set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets -of_objects [get_cells Qn_OBUF_inst_i_1]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets -of_objects [get_cells Q_OBUF_inst_i_1]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets -of_objects [get_cells Q_OBUF_inst_i_2]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets -of_objects [get_cells Q_OBUF_inst_i_3]]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets -of_objects [get_cells Q_OBUF_inst_i_4]]
#set_property ALLOW_COMBINATIONAL_LOOPS TRUE [get_nets Q_OBUF _inst_i_2]
#set_property ALLOW_COMBINATIONAL_LOOPS TRUE [get_nets Q_OBUF _inst_i_3]
#set_property ALLOW_COMBINATIONAL_LOOPS TRUE [get_nets Q_OBUF _inst_i_4]
set_property SEVERITY {Warning} [get_drc_checks LUTLP-1]
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]