set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property PACKAGE_PIN W4 [get_ports rst_n]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]

set_property IOSTANDARD LVCMOS33 [get_ports QA]
set_property IOSTANDARD LVCMOS33 [get_ports QC]
set_property IOSTANDARD LVCMOS33 [get_ports QB]
set_property PACKAGE_PIN M17 [get_ports QA]
set_property PACKAGE_PIN M16 [get_ports QB]
set_property PACKAGE_PIN M15 [get_ports QC]

set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property PACKAGE_PIN W9 [get_ports en]
