set_property IOSTANDARD LVCMOS33 [get_ports in1]
set_property IOSTANDARD LVCMOS33 [get_ports in2]
set_property IOSTANDARD LVCMOS33 [get_ports {out1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out4[0]}]
set_property PACKAGE_PIN Y9 [get_ports in1]
set_property PACKAGE_PIN W4 [get_ports in2]
set_property PACKAGE_PIN M16 [get_ports {out1[0]}]
set_property PACKAGE_PIN M15 [get_ports {out2[0]}]
set_property PACKAGE_PIN K16 [get_ports {out3[0]}]
set_property PACKAGE_PIN L16 [get_ports {out4[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports x]
set_property IOSTANDARD LVCMOS33 [get_ports y]
