# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/demorgan_bd/demorgan_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demorgan_bd || ORIG_REF_NAME==demorgan_bd} -quiet] -quiet

# IP: bd/demorgan_bd/ip/demorgan_bd_demorgan_df_0_0/demorgan_bd_demorgan_df_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demorgan_bd_demorgan_df_0_0 || ORIG_REF_NAME==demorgan_bd_demorgan_df_0_0} -quiet] -quiet

# XDC: bd/demorgan_bd/demorgan_bd_ooc.xdc
