# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const_1.xdc

# Block Designs: bd/task1/task1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task1 || ORIG_REF_NAME==task1} -quiet] -quiet

# IP: bd/task1/ip/task1_multiplexer41_0_0/task1_multiplexer41_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task1_multiplexer41_0_0 || ORIG_REF_NAME==task1_multiplexer41_0_0} -quiet] -quiet

# IP: bd/task1/ip/task1_multiplexer41_1_0/task1_multiplexer41_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task1_multiplexer41_1_0 || ORIG_REF_NAME==task1_multiplexer41_1_0} -quiet] -quiet

# IP: bd/task1/ip/task1_util_vector_logic_0_0/task1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task1_util_vector_logic_0_0 || ORIG_REF_NAME==task1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/task1/ip/task1_util_vector_logic_0_1/task1_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task1_util_vector_logic_0_1 || ORIG_REF_NAME==task1_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/task1/ip/task1_xlconstant_0_0/task1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task1_xlconstant_0_0 || ORIG_REF_NAME==task1_xlconstant_0_0} -quiet] -quiet

# IP: bd/task1/ip/task1_xlconstant_1_0/task1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task1_xlconstant_1_0 || ORIG_REF_NAME==task1_xlconstant_1_0} -quiet] -quiet

# XDC: bd/task1/task1_ooc.xdc
