# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Task_2cons.xdc

# Block Designs: bd/task2/task2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task2 || ORIG_REF_NAME==task2} -quiet] -quiet

# IP: bd/task2/ip/task2_decoder3_8_0_0/task2_decoder3_8_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task2_decoder3_8_0_0 || ORIG_REF_NAME==task2_decoder3_8_0_0} -quiet] -quiet

# IP: bd/task2/ip/task2_decoder3_8_1_0/task2_decoder3_8_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task2_decoder3_8_1_0 || ORIG_REF_NAME==task2_decoder3_8_1_0} -quiet] -quiet

# IP: bd/task2/ip/task2_xlconcat_0_0/task2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task2_xlconcat_0_0 || ORIG_REF_NAME==task2_xlconcat_0_0} -quiet] -quiet

# IP: bd/task2/ip/task2_util_vector_logic_0_1/task2_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task2_util_vector_logic_0_1 || ORIG_REF_NAME==task2_util_vector_logic_0_1} -quiet] -quiet

# XDC: bd/task2/task2_ooc.xdc
