# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# IP: ip/div/div.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div || ORIG_REF_NAME==div} -quiet] -quiet

# XDC: ip/div/div_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==div || ORIG_REF_NAME==div} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/div/div.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==div || ORIG_REF_NAME==div} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/div/div_ooc.xdc
